### ISSUE TITLE
Inviting 

### ISSUE THREAD

**Issue by mrowoc** [ToberoCat/ImprovedFactions#182] opened 2024-06-22 08:06 UTC
Inviting people to the faction does not work, after entering the command and nickname correctly, an error appears that there is no such player on the server. In addition, people without an invitation can join the faction using /f join name, thanks to which they can rob and destroy the enemy faction's base

**Comment by ToberoCat** [comment] 2024-06-22 20:20
The latest dev build includes a new command, called joinType. It lets you set if anyone can join or only people by invite. I suggest you to upgrade to this version to fix the first issue

**Comment by ToberoCat** [comment] 2024-06-22 20:25
Okay, can't reproduce being unable to invite a player. I used /f invite Tober0 Member and it worked.
Are you running in online or offline mode? Maybe there's a issue with that

**Comment by aShanki** [comment] 2024-06-23 09:40
This is reproducible in offline mode.

**Comment by ToberoCat** [comment] 2024-07-18 14:29
Has been fixed by the latest dev build pull reuqes

**Closed by ToberoCat** 2024-07-18 14:29 UTC
Labels: bug
